version: '3.4'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - challenge
    container_name: db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - challenge
    container_name: adminer

  python:
    build: 
      context: .
    networks:
      - challenge
    container_name: python

networks:
  challenge: